Helm ocp support
cyberark/conjur-oss-helm-chart pull request #71
Opened 2020-08-10 17:51 UTC by guygiat

### What does this PR do?
- Add support for helm chart installation on OCP

### What ticket does this PR close?
Connected to #[relevant GitHub issues, eg 76]

### Checklists

#### Change log
- [ ] The CHANGELOG has been updated, or
- [ ] This PR does not include user-facing changes and doesn't require a CHANGELOG update

#### Test coverage
- [ ] This PR includes new unit and integration tests to go with the code changes, or
- [ ] The changes in this PR do not require tests

#### Documentation
- [ ] Docs (e.g. `README`s) were updated in this PR, and/or there is a follow-on issue to update docs, or
- [ ] This PR does not require updating any documentation

2020-09-28 09:19 UTC, gmcbrien commented
Thanks for the OCP Support. However, in our OCP 4.5.8, we're still having Postgres problems, with the 'classic' error:

```
mkdir: cannot create directory '/var/lib/pgsql/data/userdata': Permission denied
```

2020-09-29 11:47 UTC, guygiat commented
That's weird, did you try with the following command?
helm install -n "$CONJUR_NAMESPACE" "$HELM_RELEASE" ./conjur-oss --set
openshift.enabled=true --set dataKey="$(docker run --rm cyberark/conjur
data-key generate)"

On Mon, Sep 28, 2020 at 12:19 PM Grant <notifications@github.com> wrote:

> Thanks for the OCP Support. However, in our OCP 4.5.8, we're still having
> Postgres problems, with the 'classic' error:
>
> mkdir: cannot create directory '/var/lib/pgsql/data/userdata': Permission denied
>
> Would you have any suggestions?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cyberark/conjur-oss-helm-chart/pull/71#issuecomment-699887905>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALWYSAKWHJAIN4YQZZ4SPC3SIBIJPANCNFSM4P2GKHMQ>
> .
>

2020-09-29 12:08 UTC, gmcbrien commented
The below email is classified: Internal

Hi Guy and thanks or getting back to me.

You may notice, I actually deleted my comment in your PR, just an hour or so ago. I found that your charts worked fine in a ‘playground’ Openshift cluster, so there is nothing wrong with the charts.

I have taken a deeper look and it appears it’s related to the creation of our PVs somehow. I managed to get it running this morning but am still not 100% sure what I’ve changed.

Anyway, thanks again for your useful helm charts and I’ll get back to you in case of further problems.

Grant

From: Guy Giat <notifications@github.com>
Sent: 29 September 2020 13:48
To: cyberark/conjur-oss-helm-chart <conjur-oss-helm-chart@noreply.github.com>
Cc: Grant McBrien <grant.mcbrien@deutsche-boerse.com>; Comment <comment@noreply.github.com>
Subject: Re: [cyberark/conjur-oss-helm-chart] Helm ocp support (#71)

That's weird, did you try with the following command?
helm install -n "$CONJUR_NAMESPACE" "$HELM_RELEASE" ./conjur-oss --set
openshift.enabled=true --set dataKey="$(docker run --rm cyberark/conjur
data-key generate)"

On Mon, Sep 28, 2020 at 12:19 PM Grant <notifications@github.com<mailto:notifications@github.com>> wrote:

> Thanks for the OCP Support. However, in our OCP 4.5.8, we're still having
> Postgres problems, with the 'classic' error:
>
> mkdir: cannot create directory '/var/lib/pgsql/data/userdata': Permission denied
>
> Would you have any suggestions?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cyberark/conjur-oss-helm-chart/pull/71#issuecomment-699887905>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALWYSAKWHJAIN4YQZZ4SPC3SIBIJPANCNFSM4P2GKHMQ>
> .
>


—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://github.com/cyberark/conjur-oss-helm-chart/pull/71#issuecomment-700649789>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AHRSOX64UIX4LU65XZJVTCDSIHCOZANCNFSM4P2GKHMQ>.
-----------------------------------------
Diese E-Mail enthaelt vertrauliche oder rechtlich geschuetzte Informationen.
Wenn Sie nicht der beabsichtigte Empfaenger sind, informieren Sie bitte
sofort den Absender und loeschen Sie diese E-Mail. Das unbefugte Kopieren
dieser E-Mail oder die unbefugte Weitergabe der enthaltenen Informationen
ist nicht gestattet.

The information contained in this message is confidential or protected by
law. If you are not the intended recipient, please contact the sender and
delete this message. Any unauthorised copying of this message or
unauthorised distribution of the information contained herein is prohibited.

Legally required information for business correspondence/
Gesetzliche Pflichtangaben fuer Geschaeftskorrespondenz:
http://deutsche-boerse.com/letterhead

2020-10-02 12:59 UTC, gmcbrien commented
The below email is classified: Internal

Hi again Guy,

Just curious – would you have any plans to upgrade the conjur-oss image in your charts to, say, 1.8.1?

Thanks a lot and regards,

Grant McBrien


From: Grant McBrien
Sent: 29 September 2020 14:08
To: 'cyberark/conjur-oss-helm-chart' <reply@reply.github.com>
Subject: RE: [cyberark/conjur-oss-helm-chart] Helm ocp support (#71)

The below email is classified: Internal

Hi Guy and thanks or getting back to me.

You may notice, I actually deleted my comment in your PR, just an hour or so ago. I found that your charts worked fine in a ‘playground’ Openshift cluster, so there is nothing wrong with the charts.

I have taken a deeper look and it appears it’s related to the creation of our PVs somehow. I managed to get it running this morning but am still not 100% sure what I’ve changed.

Anyway, thanks again for your useful helm charts and I’ll get back to you in case of further problems.

Grant

From: Guy Giat <notifications@github.com<mailto:notifications@github.com>>
Sent: 29 September 2020 13:48
To: cyberark/conjur-oss-helm-chart <conjur-oss-helm-chart@noreply.github.com<mailto:conjur-oss-helm-chart@noreply.github.com>>
Cc: Grant McBrien <grant.mcbrien@deutsche-boerse.com<mailto:grant.mcbrien@deutsche-boerse.com>>; Comment <comment@noreply.github.com<mailto:comment@noreply.github.com>>
Subject: Re: [cyberark/conjur-oss-helm-chart] Helm ocp support (#71)

That's weird, did you try with the following command?
helm install -n "$CONJUR_NAMESPACE" "$HELM_RELEASE" ./conjur-oss --set
openshift.enabled=true --set dataKey="$(docker run --rm cyberark/conjur
data-key generate)"

On Mon, Sep 28, 2020 at 12:19 PM Grant <notifications@github.com<mailto:notifications@github.com>> wrote:

> Thanks for the OCP Support. However, in our OCP 4.5.8, we're still having
> Postgres problems, with the 'classic' error:
>
> mkdir: cannot create directory '/var/lib/pgsql/data/userdata': Permission denied
>
> Would you have any suggestions?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cyberark/conjur-oss-helm-chart/pull/71#issuecomment-699887905>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALWYSAKWHJAIN4YQZZ4SPC3SIBIJPANCNFSM4P2GKHMQ>
> .
>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://github.com/cyberark/conjur-oss-helm-chart/pull/71#issuecomment-700649789>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AHRSOX64UIX4LU65XZJVTCDSIHCOZANCNFSM4P2GKHMQ>.
-----------------------------------------
Diese E-Mail enthaelt vertrauliche oder rechtlich geschuetzte Informationen.
Wenn Sie nicht der beabsichtigte Empfaenger sind, informieren Sie bitte
sofort den Absender und loeschen Sie diese E-Mail. Das unbefugte Kopieren
dieser E-Mail oder die unbefugte Weitergabe der enthaltenen Informationen
ist nicht gestattet.

The information contained in this message is confidential or protected by
law. If you are not the intended recipient, please contact the sender and
delete this message. Any unauthorised copying of this message or
unauthorised distribution of the information contained herein is prohibited.

Legally required information for business correspondence/
Gesetzliche Pflichtangaben fuer Geschaeftskorrespondenz:
http://deutsche-boerse.com/letterhead

2020-10-02 13:04 UTC, guygiat commented
Hi Grant,

We are in the making of a conjur image based on RedHat UBI which will be
available in the redhat registry as well as an Operator :)

On Fri, Oct 2, 2020 at 16:00 Grant <notifications@github.com> wrote:

>
>
>
> The below email is classified: Internal
>
>
>
>
>
>
>
>
>
>
>
>
>
> Hi again Guy,
>
>
>
>
>
>
>
>
>
>
>
>
>
> Just curious – would you have any plans to upgrade the conjur-oss image in
> your charts to, say, 1.8.1?
>
>
>
>
>
>
>
>
>
>
>
>
>
> Thanks a lot and regards,
>
>
>
>
>
>
>
>
>
>
>
>
>
> Grant McBrien
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
> From: Grant McBrien
>
>
>
>
>
>
> Sent: 29 September 2020 14:08
>
>
>
>
>
>
> To: 'cyberark/conjur-oss-helm-chart' <reply@reply.github.com>
>
>
>
>
>
>
> Subject: RE: [cyberark/conjur-oss-helm-chart] Helm ocp support (#71)
>
>
>
>
>
>
>
>
>
>
>
>
>
> The below email is classified: Internal
>
>
>
>
>
>
>
>
>
>
>
>
>
> Hi Guy and thanks or getting back to me.
>
>
>
>
>
>
>
>
>
>
>
>
>
> You may notice, I actually deleted my comment in your PR, just an hour or
> so ago. I found that your charts worked fine in a ‘playground’ Openshift
> cluster, so there is nothing wrong with the charts.
>
>
>
>
>
>
>
>
>
>
>
>
>
> I have taken a deeper look and it appears it’s related to the creation of
> our PVs somehow. I managed to get it running this morning but am still not
> 100% sure what I’ve changed.
>
>
>
>
>
>
>
>
>
>
>
>
>
> Anyway, thanks again for your useful helm charts and I’ll get back to you
> in case of further problems.
>
>
>
>
>
>
>
>
>
>
>
>
>
> Grant
>
>
>
>
>
>
>
>
>
>
>
>
>
> From: Guy Giat <notifications@github.com<mailto:notifications@github.com>>
>
>
>
>
>
>
> Sent: 29 September 2020 13:48
>
>
>
>
>
>
> To: cyberark/conjur-oss-helm-chart <
> conjur-oss-helm-chart@noreply.github.com<mailto:
> conjur-oss-helm-chart@noreply.github.com>>
>
>
>
>
>
>
> Cc: Grant McBrien <grant.mcbrien@deutsche-boerse.com<mailto:
> grant.mcbrien@deutsche-boerse.com>>; Comment <comment@noreply.github.com
> <mailto:comment@noreply.github.com>>
>
>
>
>
>
>
> Subject: Re: [cyberark/conjur-oss-helm-chart] Helm ocp support (#71)
>
>
>
>
>
>
>
>
>
>
>
>
>
> That's weird, did you try with the following command?
>
>
>
>
>
>
> helm install -n "$CONJUR_NAMESPACE" "$HELM_RELEASE" ./conjur-oss --set
>
>
>
>
>
>
> openshift.enabled=true --set dataKey="$(docker run --rm cyberark/conjur
>
>
>
>
>
>
> data-key generate)"
>
>
>
>
>
>
>
>
>
>
>
>
>
> On Mon, Sep 28, 2020 at 12:19 PM Grant <notifications@github.com<mailto:
> notifications@github.com>> wrote:
>
>
>
>
>
>
>
>
>
>
>
>
>
> > Thanks for the OCP Support. However, in our OCP 4.5.8, we're still having
>
>
>
>
>
>
> > Postgres problems, with the 'classic' error:
>
>
>
>
>
>
> >
>
>
>
>
>
>
> > mkdir: cannot create directory '/var/lib/pgsql/data/userdata':
> Permission denied
>
>
>
>
>
>
> >
>
>
>
>
>
>
> > Would you have any suggestions?
>
>
>
>
>
>
> >
>
>
>
>
>
>
> > —
>
>
>
>
>
>
> > You are receiving this because you authored the thread.
>
>
>
>
>
>
> > Reply to this email directly, view it on GitHub
>
>
>
>
>
>
> > <
> https://github.com/cyberark/conjur-oss-helm-chart/pull/71#issuecomment-699887905
> >,
>
>
>
>
>
>
> > or unsubscribe
>
>
>
>
>
>
> > <
> https://github.com/notifications/unsubscribe-auth/ALWYSAKWHJAIN4YQZZ4SPC3SIBIJPANCNFSM4P2GKHMQ
> >
>
>
>
>
>
>
> > .
>
>
>
>
>
>
> >
>
>
>
>
>
>
>
>
>
>
>
>
>
> —
>
>
>
>
>
>
> You are receiving this because you commented.
>
>
>
>
>
>
> Reply to this email directly, view it on GitHub<
> https://github.com/cyberark/conjur-oss-helm-chart/pull/71#issuecomment-700649789>,
> or unsubscribe<
> https://github.com/notifications/unsubscribe-auth/AHRSOX64UIX4LU65XZJVTCDSIHCOZANCNFSM4P2GKHMQ
> >.
>
>
>
>
>
>
> -----------------------------------------
>
>
>
> Diese E-Mail enthaelt vertrauliche oder rechtlich geschuetzte
> Informationen.
>
>
>
> Wenn Sie nicht der beabsichtigte Empfaenger sind, informieren Sie bitte
>
>
>
> sofort den Absender und loeschen Sie diese E-Mail. Das unbefugte Kopieren
>
>
>
> dieser E-Mail oder die unbefugte Weitergabe der enthaltenen Informationen
>
>
>
> ist nicht gestattet.
>
>
>
>
>
>
>
> The information contained in this message is confidential or protected by
>
>
>
> law. If you are not the intended recipient, please contact the sender and
>
>
>
> delete this message. Any unauthorised copying of this message or
>
>
>
> unauthorised distribution of the information contained herein is
> prohibited.
>
>
>
>
>
>
>
> Legally required information for business correspondence/
>
>
>
> Gesetzliche Pflichtangaben fuer Geschaeftskorrespondenz:
>
>
>
> http://deutsche-boerse.com/letterhead
>
>
>
>
>
>
>
>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cyberark/conjur-oss-helm-chart/pull/71#issuecomment-702719949>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALWYSANVH43DJTQ2QT5IZJ3SIXFFDANCNFSM4P2GKHMQ>
> .
>
>
>
>

2020-10-15 10:24 UTC, gmcbrien commented
Hi,
Just redeployed and am getting an error which we didn't have before:

`"/usr/bin/exec-entrypoint: line 3: exec: server: not found"`

I see the image was updated 8 days ago. Would you have any ideas?

Thanks a lot!

2020-10-15 10:49 UTC, guygiat commented
Hi Grant,

We did a couple of changes because it is still on undergoing work.
In the meantime you can try using guygiat/conjur-ubi-ocp for the
conjur image and guygiat/nginx-ubi for the nginx image.

Thanks.

On Thu, Oct 15, 2020 at 1:24 PM Grant <notifications@github.com> wrote:

> Hi,
> Just redeployed and am getting an error which we didn't have before:
>
> "/usr/bin/exec-entrypoint: line 3: exec: server: not found"
>
> I see the image was updated 8 days ago. Would you have any ideas?
>
> Thanks a lot!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cyberark/conjur-oss-helm-chart/pull/71#issuecomment-709106481>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALWYSALKGN7PYKKEELY2L33SK3EWJANCNFSM4P2GKHMQ>
> .
>

2020-12-17 16:02 UTC, diverdane reviewed
@guygiat ,
Nice work, thank you so much for adding this support!

I've tested this on our OCP setup and it works (yay!), although this setup doesn't have a storage class, so I had to test without persistence.

My one overall comment is that I'd like to try to merge (or "interleave" is probably a better way to put it) the Kubernetes and OpenShift postgres deployments and values.yaml configs. It may help to use the same approaches for both as much as possible. For example, the OpenShift uses a ConfigMap for SSL settings, and Kubernetes uses command line arguments. It would be better to pick one of these approaches for both (if providing a command + args won't work for OpenShift, I can convert the Kubernetes deployment to use a ConfigMap).

I started to try combining these deployments myself... but I suspect that you probably started with this approach and then at some point things became too divergent? I'll continue to explore this, let me know if `there be dragons` with this.

2020-12-18 20:05 UTC, diverdane reviewed
Okay, I took a shot at merging/converging the postgres YAML files for OpenShift vs Kubernetes, and it turned out to have more differences than lines in common for OCP vs K8s (which you probably knew from your experience with this postgres image).

I'm wondering if a better approach would be to use the same image that you're using for OpenShift in the generic Kubernetes platforms. Obviously we'd want your changes to merge first, and tackle the Kubernetes changes separately.

2020-12-20 12:50 UTC, guygiat commented on conjur-oss/templates/postgres-ocp.yaml
> +        - name: {{ .Release.Name }}-conjur-postgres-ssl-configmap-volume
I copied the structure of `{{ .Release.Name }}-` from the current `deployment.yaml`, I have no problem to remove it though. WDYT?

2020-12-20 13:15 UTC, guygiat commented on conjur-oss/templates/postgres-ocp.yaml
> +          name: {{ .Release.Name }}-conjur-postgres-ssl-configmap
I copied the structure of `-ssl-` from the current deployment.yaml, I have no problem to remove it though. WDYT?

2020-12-21 13:27 UTC, diverdane commented on conjur-oss/templates/postgres-ocp.yaml
> +          name: {{ .Release.Name }}-conjur-postgres-ssl-configmap
I'd have a slight preference for dropping the `-ssl-`, just in case we add more Postgres config in the future, but your call.

2020-12-21 13:40 UTC, diverdane commented on conjur-oss/templates/postgres-ocp.yaml
> +        - name: {{ .Release.Name }}-conjur-postgres-ssl-configmap-volume
Ah... Yeah, I'd say leave it the way you have it to stay consistent. At some point we should consider simplifying the volume names, seems like unnecessary complexity.

2020-12-21 13:57 UTC, diverdane reviewed
I forgot to mention, any changes we make to the `values.yaml` will need corresponding
sanity checks added to the `values.schema.json`

2020-12-21 15:21 UTC, guygiat commented on conjur-oss/templates/postgres-ocp.yaml
> +        - name: {{ .Release.Name }}-conjur-postgres-ssl-configmap-volume
agree

2020-12-21 17:08 UTC, izgeri requested changes
@guygiat this change is going to need an entry in CHANGELOG.md. I would suggest something like this under `Added`:
> The Conjur OSS helm chart has Community support for deploying Conjur OSS to OpenShift 4.x. [cyberark/conjur-oss-helm-chart#60](https://github.com/cyberark/conjur-oss-helm-chart/issues/60)

2020-12-21 17:08 UTC, izgeri commented on conjur-oss/README.md
> +- OCP 4.x+
we are going to need to add a note here that this is community support for now, until our OCP clusters are able to support persistent volumes for automated testing.
```suggestion
- OCP 4.x+ (**Preliminary [Community level](https://github.com/cyberark/community/blob/master/Conjur/conventions/certification-levels.md#community) support) only**)
```

2020-12-21 18:20 UTC, izgeri approved these changes
The changes I requested are all set - @diverdane I leave the rest to your technical review.

2020-12-22 15:08 UTC, diverdane requested changes
Hi @guygiat ,
I'm trying to test these changes on a local Kubernetes cluster to make sure that we're not
causing any regressions, but I'm seeing some issues when I try to log into Conjur from a Conjur CLI pod:

```
root@conjur-cli-5bc479754b-tx92r:~# conjur authn login -u admin -p XXXXXX
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
error: 502 Bad Gateway
root@conjur-cli-5bc479754b-tx92r:~#
```
This could be operator error on my part, but can you hold off on merging this until I get a chance to figure out what's happening here?

2020-12-22 15:29 UTC, guygiat commented
BTW, I don't have write access to this repo so you or Geri will have to merge it :)

2020-12-22 15:49 UTC, guygiat commented
> Hi @guygiat ,
> I'm trying to test these changes on a local Kubernetes cluster to make sure that we're not
> causing any regressions, but I'm seeing some issues when I try to log into Conjur from a Conjur CLI pod:
> 
> ```
> root@conjur-cli-5bc479754b-tx92r:~# conjur authn login -u admin -p XXXXXX
> <html>
> <head><title>502 Bad Gateway</title></head>
> <body>
> <center><h1>502 Bad Gateway</h1></center>
> <hr><center>nginx</center>
> </body>
> </html>
> error: 502 Bad Gateway
> root@conjur-cli-5bc479754b-tx92r:~#
> ```
> 
> This could be operator error on my part, but can you hold off on merging this until I get a chance to figure out what's happening here?

fix in my last commit :)

2020-12-23 19:06 UTC, diverdane approved these changes
LGTM!

2020-12-23 19:07 UTC, merged